###admin api reqs
post http://localhost:4000/admin-api/adminregistration
Content-Type: application/json

{
    "userType":"admin",
    "username":"sunny-admin",
    "password":"sunny",
    "email":"sunny@mail.com"
}

###
post http://localhost:4000/admin-api/adminlogin
Content-Type: application/json

{
    "userType":"admin",
    "username":"dev-admin",
    "password":"dev"
}

###
get http://localhost:4000/admin-api/view-articles

