
###author api reqs
post http://localhost:4000/author-api/authorregistration
Content-Type: application/json

{
    "userType":"author",
    "username":"sunny-author",
    "password":"sunny",
    "email":"dev@mail.com"
}

###
post http://localhost:4000/author-api/authorlogin
Content-Type: application/json

{
    "userType":"author",
    "username":"dev-author",
    "password":"dev"
}


###add new article by author
post http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"Fundamentals of js",
    "category":"programming",
    "content":"javascript, often abbreviated as JS, is a programming language and core technology of the Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior Web browsers have a dedicated JavaScript engine that executes the client code. These engines are also utilized in some servers and a variety of apps. The most popular runtime system for non-browser usage is Node.js.",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"dev",
    "comments":[],
    "status":true
}


###modifying article by author
put http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"1729314116",
    "title":"Fundamentals of js",
    "category":"programming",
    "content":"javascript is a programming language and core technology of the Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior Web browsers have a dedicated JavaScript engine that executes the client code. These engines are also utilized in some servers and a variety of apps. The most popular runtime system for non-browser usage is Node.js.",
    "dateOfCreation":"2024-10-19T05:01:56.414Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"dev",
    "comments":[],
    "status":true
}

###delete(soft delete) the article by id
put http://localhost:4000/author-api/article/1729314116
Content-Type: application/json

{
    "articleId":"1729314116",
    "title":"Fundamentals of js",
    "category":"programming",
    "content":"javascript is a programming language and core technology of the Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior Web browsers have a dedicated JavaScript engine that executes the client code. These engines are also utilized in some servers and a variety of apps. The most popular runtime system for non-browser usage is Node.js.",
    "dateOfCreation":"2024-10-19T05:01:56.414Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"dev",
    "comments":[],
    "status":false
}



###
get http://localhost:4000/author-api/view-articles/dev