###user api reqs
post http://localhost:4000/user-api/userregistration
Content-Type: application/json

{
    "userType":"user",
    "username":"dev",
    "password":"dev",
    "email":"dev@mail.com"
}

###
post http://localhost:4000/user-api/userlogin
Content-Type: application/json

{
    "userType":"user",
    "username":"dev",
    "password":"dev"
}

###
get http://localhost:4000/user-api/view-articles


### write comment
post http://localhost:4000/user-api/comment/1729319484
Content-Type: application/json

{
    
    "username":"dev",
    "comment":"amazing content"
}
